# Generated by Django 2.2.5 on 2021-01-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210124_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_secrete_code',
            new_name='email_secrete',
        ),
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'Github'), ('kakao', 'Kakao')], default='email', max_length=50),
        ),
    ]
