# Generated by Django 2.2.5 on 2020-12-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201231_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='supperhost',
            new_name='superhost',
        ),
        migrations.RemoveField(
            model_name='user',
            name='curency',
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('krw', 'KRW')], max_length=3, null=True),
        ),
    ]
